General:
  IncludeFD: false
  IncludeND: true
  IncludeNDGAr: true
  FDPOT: 1.3628319e+23
  NDPOT: 1.0e+21
#  NDPOT: 1.1e+21
 #### Asimov A ####
  OscParams: [0.307, 0.528, 0.0218, 7.53e-5, 2.509e-3, -1.601]
  # NuFit 4.0 NH ####
  #OscParams: [0.310, 0.582, 0.0224, 7.39e-5, 2.525e-3, -2.498]
  Systematics:
    XsecCovFile: "inputs/xsec_covariance_DUNE_systs_NDGAr_new_allparams.root"
    XsecCovName: "xsec_cov"
    XsecStepScale: 0.1
    XsecAtGen: false
    OscCovFile: "inputs/osc_covariance_DUNE_PDG2021_v1.root"
    OscCovName: "osc_cov"
    OscStepScale: 0.045
  Output:
    FileName: LLHScans_CC_NDGArandNDLAr_firsttry.root
LLHScans:
  ParPoints: 100
