General:
  OutputFile: "parameter_study_sterile/test_2d_var/test_var_sterile_all_param_thetav1_dm41_1e-3_nue_numu_selec_recoE_recoCos.root"

  DUNESamples: ["configs/Samples/AtmSample_nueselec.yaml", "configs/Samples/AtmSample_numuselec.yaml"]

  #Nu-FIT
  #OscillationParameters: [0.310, 0.582, 0.224, 7.39E-5, 2.5254E-3, -2.498, 25]

  #Nu-FIT 5.2 w. SK atm
  #OscillationParameters: [0.303, 0.451, 0.02225, 7.41E-5, 2.45E-3, -2.233]
  OscillationParameters: [0.303, 0.451, 0.02225, 7.41E-5, 2.45E-3, -2.233, 0., 0., 0., 0.001, 0., 0.]
  #OscillationParameters: [0.303, 0.451, 0.02225, 7.41E-5, 2.45E-3, -2.233, -0.5, 0.2, 0.4, 0.3, 0.5, 0.25, 0., 0., 0., 0.2, 0.4, 0.4]

  #T2K-like best-fit
  #OscillationParameters: [0.307, 0.528, 0.0218, 7.53e-5, 2.509e-3, -1.601, 25]
  
  Systematics:
    XsecCovFile: ["configs/CovObjs/xsec_covariance_DUNE_systs_2022a_FD_v3.yaml"]
    XsecCovName: "xsec_cov"
    XsecStepScale: 0.1
    XsecAtGen: false 
    OscCovFile: ["configs/CovObjs/OscProb_test.yaml"]
    OscCovName: "osc_cov"

  Fitter:
    FitTestLikelihood: false

  MCMC:
    NSteps: 2000
    AutoSave: 10000

  Output:
    FileName: "TestEventRates.root"
    OUTPUTNAME: "TestLLH.root"

  ProcessMCMC: No
  Seed: 0
  Debug: No

"Variations": [
    {
      "Name": "sin2th_14",
      #"OscParDefault": [0.303, 0.451, 0.02225, 7.41E-5, 2.45E-3, -2.233, 0., 0., 0., 0.001, 0., 0.],
      "VarValues": [0., 0.001, 0.005, 0.01, 0.05, 0.1, 0.5],
    },

    {
      "Name": "sin2th_24",
      #"OscParDefault": [0.303, 0.451, 0.02225, 7.41E-5, 2.45E-3, -2.233, 0., 0., 0., 0.001, 0., 0.],
      "VarValues": [0., 0.001, 0.005, 0.01, 0.05, 0.1, 0.5],
    },

    {
      "Name": "sin2th_34",
      #"OscParDefault": [0.303, 0.451, 0.02225, 7.41E-5, 2.45E-3, -2.233, 0., 0., 0., 0.001, 0., 0.],
      "VarValues": [0., 0.001, 0.005, 0.01, 0.05, 0.1, 0.5],
    },

    {
      "Name": "delm2_14",
      "OscParDefault": [0.303, 0.451, 0.02225, 7.41E-5, 2.45E-3, -2.233, 0.03, 0.06, 0.05, 0.001, 0., 0.],
      "VarValues": [0., 0.00001, 0.0001, 0.001, 0.01, 0.1, 1.],
    },

    {
      "Name": "delta_14",
      "OscParDefault": [0.303, 0.451, 0.02225, 7.41E-5, 2.45E-3, -2.233, 0.03, 0.06, 0.05, 0.001, 0., 0.],
      "VarValues": [-2.35619449019, -1.57079632679, -0.78539816339, 0., 0.78539816339, 1.57079632679, 2.35619449019, 3.14159265],
    },

    {
      "Name": "delta_24",
      "OscParDefault": [0.303, 0.451, 0.02225, 7.41E-5, 2.45E-3, -2.233, 0.03, 0.06, 0.05, 0.001, 0., 0.],
      "VarValues": [-2.35619449019, -1.57079632679, -0.78539816339, 0., 0.78539816339, 1.57079632679, 2.35619449019, 3.14159265],
    }

]

"Projections": [
  {
    "Name": "RecoNuEnergy", 
    "VarString": "RecoNeutrinoEnergy",
    "VarBins": [0.0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.2,1.4],
    "KinematicCuts": [
      {
        "Range": [0.1,0.8],
        "Name": "TrueNuEnergy", 
        "VarString": "TrueNeutrinoEnergy"
      }, 
      {
        "Range": [0.4,1.0],
        "Name": "TrueCosZ", 
        "VarString": "TrueCosineZ"
      }
    ], 
    "CategoryCuts": [
      {
        "Name": "OscillationChannel_Single", 
        "VarString": "OscChannel",
        "Breakdown": [[0.0],  [1.0],  [2.0],  [3.0],  [4.0],  [5.0],  [6.0],  [7.0],  [8.0],  [9.0], [10.0], [11.0]],
	"Names":     ["nue_x_nue","nue_x_numu","nue_x_nutau","numu_x_nue","numu_x_numu","numu_x_nutau","nuebar_x_nuebar","nuebar_x_numubar","nuebar_x_nutaubar","numubar_x_nuebar","numubar_x_numubar","numubar_x_nutaubar"],
      },
      {
        "Name": "OscillationChannel_Group", 
        "VarString": "OscChannel",
        "Breakdown": [[0.0, 1.0, 2.0, 3.0, 4.0, 5.0],  [6.0, 7.0, 8.0, 9.0, 10.0, 11.0]],
	"Names":     ["Nu","Nubar"],
      },
      {
        "Name": "Mode_Single", 
        "VarString": "Mode",
        "Breakdown": [[0.0] , [1.0], [2.0], [3.0], [4.0], [5.0], [6.0], [7.0], [8.0], [9.0], [10.0], [11.0], [12.0], [13.0], [14.0], [15.0], [16.0], [17.0], [18.0], [19.0], [20.0], [21.0], [22.0], [23.0], [24.0], [25.0], [26.0]],
      },
      {
        "Name": "Mode_Group", 
        "VarString": "Mode",
        "Breakdown": [ [0.0],   [2.0],   [3.0],   [9.0],  [15.0],  [16.0], [1.0, 4.0, 5.0, 6.0, 7.0, 8.0, 10.0, 11.0, 12.0, 13.0], [14.0, 17.0, 18.0, 19.0, 20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0]],
	"Names":     ["CCQE", "CCDIS", "CCRES", "CCMEC", "NCDIS", "NCRES",                                                "CCOth",                                                            "NCOth"],
      }
    ],
  },

  {
    "Name": "TrueNuEnergy",
    "VarString": "TrueNeutrinoEnergy",
    "VarBins": [0.0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0,1.2,1.4,1.6,1.8,2.0,2.2,2.4,2.6,2.8,3.0,3.5,4.0,4.5,5.0,6.0,7.0,8.0,9.0,10.0],
  }
]
